#!/usr/bin/env bash

# SCRIPT_NAME="cec-toolbox"
DEVICE_NAME="PC"
CONFIG_PATH="/etc/cec-toolbox.conf"
if [[ -f $CONFIG_PATH ]]; then
    # shellcheck source=/etc/cec-toolbox.conf
    . $CONFIG_PATH
fi
CONFIG_PATH="/etc/cec-toolbox.conf"
EXE="cec-ctl -st0"
COMMAND=$1

configure_playback() {
    $EXE --playback -o "$1"
    sleep .2s
}

get_physical_address() {
    $EXE -x
}

get_address() {
    if [[ $CUSTOM_ADDRESS =~ [0-9].[0-9].[0-9].[0-9] ]]; then
        echo "$CUSTOM_ADDRESS"
        return
    fi

    get_physical_address
}

switch_input() {
    [[ -z "$1" ]] && return 1
    $EXE --active-source phys-addr="$1"
}

get_tv_state() {
    $EXE --give-device-power-status | grep -c "pwr-state: on"
}

tv_on() {
    configure_playback "$DEVICE_NAME"
    [[ "$(get_tv_state)" -eq 0 ]] && $EXE --image-view-on
    switch_input "$(get_address)"
}

tv_off() {
    configure_playback "$DEVICE_NAME"
    [[ "$(get_tv_state)" -ne 0 ]] && $EXE --standby
}

poweroff() {
    /usr/bin/systemctl list-jobs |
        grep -e 'reboot.target.*start' &&
        echo "Rebooting, skip TV standby" ||
        tv_off
}

write_config() {
    [[ $1 == "address" ]] && CUSTOM_ADDRESS="$2"
    [[ $1 == "name" ]] && DEVICE_NAME="$2"

    echo "# Values are optional" > "$CONFIG_PATH"
    echo "CUSTOM_ADDRESS=$CUSTOM_ADDRESS" >> "$CONFIG_PATH"
    echo "DEVICE_NAME=$DEVICE_NAME" >> "$CONFIG_PATH"
}

case "$COMMAND" in
    "on")
        tv_on
        ;;
    "off")
        tv_off
        ;;
    "poweroff")
        poweroff
        ;;
    "input")
        switch_input "${2}.0.0.0"
        ;;
    "get-input")
        get_physical_address | cut -d "." -f 1
        ;;
    "address")
        get_address
        ;;
    "physical-address")
        get_physical_address
        ;;
    "configure")
        configure_playback "$DEVICE_NAME"
        ;;
    "notice-me")
        configure_playback "$DEVICE_NAME"
        switch_input "$(get_address)"
        ;;
    "set-custom-address")
        write_config "address" "$2"
        ;;
    "set-custom-name")
        write_config "name" "$2"
        ;;
    "clear-config")
        rm "$CONFIG_PATH"
        ;;
    "daemon")
        python3 input-daemon || python3 /usr/share/cec-toolbox/input-daemon
        ;;
    *)
        echo "Unknwon command: $COMMAND"
        ;;
esac
